In [1]:
import pandas as pd

# Load the cleaned data
df_ltv = pd.read_csv("../data/telco_churn_cleaned.csv")

print(df_ltv.shape)
df_ltv.head()

(7043, 21)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [2]:
print(df_ltv[[
    "tenure",
    "MonthlyCharges",
    "TotalCharges",
    "Churn"
]].head())

   tenure  MonthlyCharges  TotalCharges Churn
0       1           29.85         29.85    No
1      34           56.95       1889.50    No
2       2           53.85        108.15   Yes
3      45           42.30       1840.75    No
4       2           70.70        151.65   Yes

In [3]:
print(df_ltv[[
    "tenure",
    "MonthlyCharges",
    "TotalCharges"
]].describe())

            tenure  MonthlyCharges  TotalCharges
count  7043.000000     7043.000000   7043.000000
mean     32.371149       64.761692   2279.734304
std      24.559481       30.090047   2266.794470
min       0.000000       18.250000      0.000000
25%       9.000000       35.500000    398.550000
50%      29.000000       70.350000   1394.550000
75%      55.000000       89.850000   3786.600000
max      72.000000      118.750000   8684.800000

In [4]:
df_ltv["historical_ltv"] = (
    df_ltv["MonthlyCharges"] * df_ltv["tenure"]
)

df_ltv[[
    "tenure",
    "MonthlyCharges",
    "historical_ltv"
]].head()

   tenure  MonthlyCharges  historical_ltv
0       1           29.85           29.85
1      34           56.95         1936.30
2       2           53.85          107.70
3      45           42.30         1903.50
4       2           70.70          141.40

In [5]:
df_ltv["monthly_revenue"] = df_ltv["MonthlyCharges"]

In [6]:
df_ltv["predicted_ltv"] = (
    df_ltv["MonthlyCharges"] *
    (df_ltv["tenure"] + 12)
)